# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
stages:
- stage: Build
  jobs:
  - job: macOS
    pool:
      name: BlueQuartz Self Hosted
    steps:
    - script: |
        echo System.PullRequest.SourceBranch=$(System.PullRequest.SourceBranch)
        echo System.PullRequest.PullRequestNumber=$(System.PullRequest.PullRequestNumber)
        echo Build.SourceBranchName=$(Build.SourceBranchName)
        echo Build.Repository.Name=$(Build.Repository.Name)
        echo Build.Repository.Uri=$(Build.Repository.Uri)
      displayName: 'Dump Azure Variables'
    - script: |
        branch=$(System.PullRequest.SourceBranch)
        mkdir ExternalProjects
        cd ExternalProjects 
        /usr/bin/git clone https://github.com/bluequartzsoftware/CMP.git
        cd CMP
        git fetch --all
        remote=`git branch -a | grep "${branch}" | wc -l`
        if [ ${remote} == 1 ]; then
          git checkout -b ${branch} --track origin/${branch}
        fi
        cd ../
        /usr/bin/git clone https://github.com/bluequartzsoftware/SIMPL.git
        /usr/bin/git clone https://github.com/bluequartzsoftware/SIMPLView.git
        mkdir Plugins
        cd Plugins
        /usr/bin/git clone https://github.com/bluequartzsoftware/ITKImageProcessing.git
        /usr/bin/git clone https://github.com/bluequartzsoftware/SimulationIO.git
        /usr/bin/git clone https://github.com/bluequartzsoftware/ZeissImport.git
        /usr/bin/git clone https://github.com/DREAM3D/Anisotropy.git
        /usr/bin/git clone https://github.com/DREAM3D/DDDAnalysisToolbox.git
        /usr/bin/git clone https://github.com/DREAM3D/DREAM3DReview.git
        /usr/bin/git clone https://github.com/DREAM3D/HEDMAnalysis.git
        /usr/bin/git clone https://github.com/DREAM3D/ImageProcessing.git
        /usr/bin/git clone https://github.com/DREAM3D/MASSIFUtilities.git
        /usr/bin/git clone https://github.com/DREAM3D/TransformationPhase.git
        /usr/bin/git clone https://github.com/DREAM3D/UCSBUtilities.git
      displayName: 'clone the Source codes'
    - script: |
        cd $(Build.BinariesDirectory)
        rm CMakeCache.txt
        /Users/Shared/DREAM3D_SDK/cmake-3.14.2-Darwin-x86_64/CMake.app/Contents/bin/cmake -G Ninja -DDREAM3D_SDK=$(Agent.BuildDirectory) -DCMAKE_BUILD_TYPE=Release $(Build.Repository.LocalPath)
      displayName: 'Configure DREAM3D....'
    - script: |
        cd $(Build.BinariesDirectory)
        /Users/Shared/DREAM3D_SDK/cmake-3.14.2-Darwin-x86_64/CMake.app/Contents/bin/cmake --build .
      displayName: 'Build DREAM3D....'
    - script: |
        cd $(Build.BinariesDirectory)
        /Users/Shared/DREAM3D_SDK/cmake-3.14.2-Darwin-x86_64/CMake.app/Contents/bin/ctest --build-and-test --test-model Continuous
      displayName: 'ctest --build-and-test  --test-model Continuous'


