SET (MXA_HDF5_SRCS
  ${PROJECT_CODE_DIR}/MXA/HDF5/H5Lite.cpp
  ${PROJECT_CODE_DIR}/MXA/HDF5/H5Utilities.cpp
)

SET (MXA_HDF5_HDRS
  ${PROJECT_CODE_DIR}/MXA/HDF5/H5Lite.h
  ${PROJECT_CODE_DIR}/MXA/HDF5/H5Utilities.h
)
cmp_IDE_SOURCE_PROPERTIES( "MXA/HDF5" "${MXA_HDF5_HDRS}" "${MXA_HDF5_SRCS}" "0")

if ( ${MXA_INSTALL_FILES} EQUAL 1 )
    INSTALL (FILES ${MXA_HDF5_HDRS}
            DESTINATION include/MXA/HDF5
            COMPONENT Headers   )
endif()
