#--- Set the DREAM3D_SDK to the current directory. This is all hard coded
set(DREAM3D_SDK "/Users/Shared/Dashboards")


set(BUILD_SHARED_LIBS ON CACHE BOOL "")
set(DREAM3D_SDK_ROOT "/Users/Shared/Toolkits")
set(DREAM3D_DATA_DIR ${DREAM3D_SDK_ROOT}/DREAM3D_Data CACHE PATH "")
set(QT_QMAKE_EXECUTABLE "${DREAM3D_SDK_ROOT}/Qt-4.8.6/bin/qmake" CACHE FILEPATH "")
set(EIGEN_INSTALL "${DREAM3D_SDK_ROOT}/Eigen-3.1.2" CACHE PATH "")
set(QWT_INSTALL "${DREAM3D_SDK_ROOT}/Qwt-5.2.2" CACHE PATH "")
set(HDF5_INSTALL "${DREAM3D_SDK_ROOT}/hdf5-1.8.13" CACHE PATH "")
set(BOOST_ROOT "${DREAM3D_SDK_ROOT}/boost-1.55.0" CACHE PATH "")
set(TBB_INSTALL_DIR  "${DREAM3D_SDK_ROOT}/tbb42_20140601oss" CACHE PATH "")
set(SIMPL_USE_MULTITHREADED_ALGOS ON CACHE BOOL "")
set(TBB_ARCH_TYPE "intel64" CACHE STRING "")
set(ITK_DIR "${DREAM3D_SDK_ROOT}/ITK-4.5.1")

set(DREAM3D_EXTRA_PLUGINS "ImageProcessing;TransformationPhase")

set(CTEST_SITE "OSX1068.bluequartz.net")
set(CTEST_BUILD_NAME "OSX168-Xcode326")
set(CTEST_CONFIGURATION_TYPE Debug)
set(CTEST_CMAKE_GENERATOR "Unix Makefiles")


