site_name: DREAM.3D
theme:
  name: 'material'
  custom_dir: '${DREAM3DProj_SOURCE_DIR}/Documentation/material-dream3d'
  palette:
    primary: light-blue
    accent: light-blue
repo_url: https://github.com/bluequartzsoftware/dream3d/
use_directory_urls: false
docs_dir: ReferenceManual
site_dir: '${HTML_OUTPUT_DIR}'

markdown_extensions:
    - toc:
        permalink: True

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

extra:
  palette:
    primary: 'blue'
    accent: 'bluegrey'

extra_css:
  - 'assets/stylesheets/extra.css'
